export const txlx={
    WDTX_SPFH:{
        label:'订单发货',
        context:[
            {key:'ddh',text:'订单号'},
            {key:'ddzt',text:'订单状态'},
            {key:'spxx',text:'商品'}
        ],
        color:'#0C8900'
    },
    WDTX_KHPJ:{
        label:'客户评价',
        context:[
            {key:'userName',text:'用户名称'},
            {key:'ddh',text:'订单号'},
            {key:'pj',text:'评价'}
        ],
        color:'#33CCFF'
    },
    WDTX_KCYJ:{
        label:'库存预警',
        context:[
            {key:'name',text:'商品'},
            {key:'kskc',text:'库存数量'},
            {key:'kcyjsl',text:'库存预警数量'}
        ],
        color:'#FFCC66'
    },
    WDTX_SPQH:{
        label:'商品缺货',
        context:[
            {key:'name',text:'商品'},
            {key:'kskc',text:'库存数量'},
            {key:'spzt',text:'商品状态'}
        ],
        color:'#FF0000'
    },
    WDTX_BOX_WELCOME:{
        label:'会员到店',
        context:[
            {key:'dpName',text:'店铺名称'},
            {key:'hyname',text:'客户名称'}
        ],
        color:'#75878a'
    },
    WDTX_DDSH:{
        label:'订单收货',
        context:[
            {key:'ddh',text:'订单号'},
            {key:'ddzt',text:'订单状态'},
            {key:'spxx',text:'商品'}
        ],
        color:'#0C8900'
    },
    WDTX_DDTK:{
        label:'订单退款',
        context:[
            {key:'ddh',text:'订单号'},
            {key:'ddzt',text:'订单状态'},
            {key:'spxx',text:'商品'}
        ],
        color:'#0C8900'
    }
}